# Generated by Django 6.0.8 on 2026-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apifySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=120)),
                ('dataset_id', models.CharField(max_length=120)),
                ('status', models.CharField(default='Unknown', max_length=120)),
            ],
        ),
    ]
