# Generated by Django 5.2.4 on 2026-09-24 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifysnapshot',
            name='_status',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='apifysnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apifysnapshot',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apifysnapshot',
            name='records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apifysnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apifysnapshot',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
