# Generated by Django 5.2.4 on 2026-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_apifysnapshot__status_apifysnapshot_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifysnapshot',
            name='progress_check_count',
            field=models.IntegerField(default=0),
        ),
    ]
