# Generated by Django 5.2.4 on 2026-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_apifysnapshot_progress_check_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apifysnapshot',
            name='_status',
        ),
    ]
