# Generated by Django 5.2.4 on 2026-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=120)),
                ('url', models.URLField(db_index=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
