# Generated by Django 6.0.8 on 2026-09-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditpost',
            old_name='date_posted',
            new_name='created_utc',
        ),
    ]
