# Generated by Django 5.2.4 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_rename_date_posted_redditpost_created_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
